### ISSUE TITLE
Issue: I don't know whats going on

### ISSUE THREAD

**Issue by Vulcran** [1213-Throwback/Project_4#2]

**Comment by DiegoLopezInc** [comment]
Real.

**Comment by albert-bastakoti** [comment]
real.

**Comment by DiegoLopezInc** [comment]
**Thankfully, we know what we are doing now!!!**
![image](https://github.com/1213-Throwback/Project_4/assets/123400127/6bde8fe4-cc79-441e-9258-45eb9bb041f2)
