### ISSUE TITLE
Problem #2 Thread 

### ISSUE THREAD

**Issue by ghost** [1213-Throwback/Project_4#6]
**Goal -** Create a new component

**Important -** Reference the p2.html file 

**Steps:**

1. Create a new component view that will display the names of all states containing a given substring. Your view must implement an input field that accepts a substring. The view will display in alphabetical order an HTML list of all states whose names contain the given substring (ignoring differences in case). For example, the view for the substring of "al" should list the states Alabama, Alaska, and California. The list should automatically update after each character that the user types in. 
2. The page should also display the substring that was used to filter the states in a new element separate from the input field. If there are no matching states then the web page should display a message indicating that fact (rather than just showing nothing). All states should be displayed when the substring is empty.
![image](https://github.com/1213-Throwback/Project_4/assets/112581503/77d5ce6b-d79f-4246-b759-5bcf6f61603b)

**Breakdown:** 

1. We want to create a new component view in the p2.html file that we can use to display the state names from the states.js file. It needs to accept the js file as an input field and display all states in alphabetical order.

2. The view must also display the substring that we use to filter the state strings from the states.js file into the new element. If no states match then our webpage should indicate that through a displayed message. If this substring is empty all states should be displayed.

**Comment by ghost** [comment]
As a team coder, I want to try and complete the code necessary for the component in Problem #2. My goal is to only complete the javascript side of this problem without having to worry about the required CSS yet.

**Comment by ghost** [comment]
Update: 

I have written most of the code and I think it should work. I am still having problems with testing so I am pushing my changes and hoping someone will pick up where I left off by testing both problems 1 and 2. Here are some snippets from the code I made. 

These are the constants that I declared: 

![image](https://github.com/1213-Throwback/Project_4/assets/112581503/082bb588-8508-4614-98af-2361c5eb46b4)

And this is the actual render: 

![image](https://github.com/1213-Throwback/Project_4/assets/112581503/7cff1c76-e10d-4878-85c4-f6c9b80cbd22)

**Comment by ghost** [comment]
Update: After looking over the solution file, I decided to push that solution. Comparing it to the code that I created, it shares similar logic, the only difference is how the solution is split into two files (p2.jsx and states.jsx) and my code was only in p2.jsx. I was not able to figure out exactly what was causing my code to not work but I understand what the solution is doing

**Comment by DiegoLopezInc** [comment]
**Problem 3 DONE**: Added Header.css & Header.jsx (from solutions) for problem two. Also got States.css working with solution for problem two...it was this one line of code..... 
![image](https://github.com/1213-Throwback/Project_4/assets/123400127/669bccd9-2eea-4402-89c4-416d07886a64)


Here's what the final outcome it looks like:
![image](https://github.com/1213-Throwback/Project_4/assets/123400127/cd3cca83-de56-4d93-bc7a-e03b89321b1b)
